### ISSUE TITLE
MNIST lasagne example

### ISSUE THREAD

**Issue by MartinThoma** [dnouri/nolearn#116]
I would like to add a little bit of documentation to the Lasagne part. I created the following code which should train a simple MLP for MNIST. However, it always fails. The problem seems to be the shape of `y` in line 55.

When I try `y = y.reshape((N, ))`, I get:

```bash
# Neural Network with 924730 learnable parameters

## Layer information

  #  name      size
---  ------  ------
  0  input     9216
  1  hidden     100
  2  output      30

Traceback (most recent call last):
  File "mnistnolearn.py", line 99, in <module>
    main()
  File "mnistnolearn.py", line 96, in main
    nn_example(testing, testing)
  File "mnistnolearn.py", line 81, in nn_example
    net1.fit(training_data['x'], training_data['y'])
  File "/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py", line 321, in fit
    self.train_loop(X, y)
  File "/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py", line 368, in train_loop
    self.train_iter_, Xb, yb)
  File "/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py", line 422, in apply_batch_func
    return func(Xb) if yb is None else func(Xb, yb)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: Shape mismatch: x has 784 cols (and 128 rows) but y has 9216 rows (and 100 cols)
Apply node that caused the error: Dot22(input.input, hidden.W)
Inputs types: [TensorType(float32, matrix), TensorType(float32, matrix)]
Inputs shapes: [(128, 784), (9216, 100)]
Inputs strides: [(3136, 4), (400, 4)]
Inputs values: ['not shown', 'not shown']

Debugprint of the apply node: 
Dot22 [@A] <TensorType(float32, matrix)> ''   
 |input.input [@B] <TensorType(float32, matrix)>
 |hidden.W [@C] <TensorType(float32, matrix)>

Storage map footprint:
 - TensorConstant{0.5}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - input.input, Shape: (128, 784), ElemSize: 4 Byte(s), TotalSize: 401408 Byte(s)
 - TensorConstant{0.00999999977648}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4.0 Byte(s)
 - <TensorType(float32, vector)>, Shape: (30,), ElemSize: 4 Byte(s), TotalSize: 120 Byte(s)
 - y_batch, Shape: (128,), ElemSize: 4 Byte(s), TotalSize: 512 Byte(s)
 - hidden.W, Shape: (9216, 100), ElemSize: 4 Byte(s), TotalSize: 3686400 Byte(s)
 - hidden.b, Shape: (100,), ElemSize: 4 Byte(s), TotalSize: 400 Byte(s)
 - output.W, Shape: (100, 30), ElemSize: 4 Byte(s), TotalSize: 12000 Byte(s)
 - TensorConstant{(1,) of 0.01}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - <TensorType(float32, matrix)>, Shape: (9216, 100), ElemSize: 4 Byte(s), TotalSize: 3686400 Byte(s)
 - <TensorType(float32, vector)>, Shape: (100,), ElemSize: 4 Byte(s), TotalSize: 400 Byte(s)
 - output.b, Shape: (30,), ElemSize: 4 Byte(s), TotalSize: 120 Byte(s)
 - <TensorType(float32, matrix)>, Shape: (100, 30), ElemSize: 4 Byte(s), TotalSize: 12000 Byte(s)
 - TensorConstant{(1,) of 0.9}, Shape: (1,), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of 0.9}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)
 - TensorConstant{(1, 1) of 0.5}, Shape: (1, 1), ElemSize: 4 Byte(s), TotalSize: 4 Byte(s)

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
```

When I try `y = y.flatten()`, I get the same as for `y = y.reshape((N, ))`.

When I try `y = y.reshape((N, 1))`, I get:

```bash
(10000, 784)
(10000, 1)
/usr/local/lib/python2.7/dist-packages/Lasagne-0.1.dev-py2.7.egg/lasagne/layers/helper.py:69: UserWarning: get_all_layers() has been changed to return layers in topological order. The former implementation is still available as get_all_layers_old(), but will be removed before the first release of Lasagne. To ignore this warning, use `warnings.filterwarnings('ignore', '.*topo.*')`.
  warnings.warn("get_all_layers() has been changed to return layers in "
Traceback (most recent call last):
  File "mnistnolearn.py", line 98, in <module>
    main()
  File "mnistnolearn.py", line 95, in main
    nn_example(testing, testing)
  File "mnistnolearn.py", line 81, in nn_example
    net1.fit(training_data['x'], training_data['y'])
  File "/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py", line 321, in fit
    self.train_loop(X, y)
  File "/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py", line 328, in train_loop
    X, y, self.eval_size)
  File "/usr/local/lib/python2.7/dist-packages/nolearn-0.6adev-py2.7.egg/nolearn/lasagne/base.py", line 448, in train_test_split
    kf = StratifiedKFold(y, round(1. / eval_size))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py", line 434, in __init__
    label_test_folds = test_folds[y == label]
IndexError: too many indices for array
```

The code:

```python
#!/usr/bin/env python

from lasagne import layers
from lasagne.updates import nesterov_momentum
from nolearn.lasagne import NeuralNet

import sys
import os
import gzip
import pickle
import numpy
import theano
import theano.tensor as T
import lasagne

PY2 = sys.version_info[0] == 2

if PY2:
    from urllib import urlretrieve

    def pickle_load(f, encoding):
        return pickle.load(f)
else:
    from urllib.request import urlretrieve

    def pickle_load(f, encoding):
        return pickle.load(f, encoding=encoding)

DATA_URL = 'http://deeplearning.net/data/mnist/mnist.pkl.gz'
DATA_FILENAME = 'mnist.pkl.gz'


def _load_data(url=DATA_URL, filename=DATA_FILENAME):
    """Load data from `url` and store the result in `filename`."""
    if not os.path.exists(filename):
        print("Downloading MNIST dataset")
        urlretrieve(url, filename)

    with gzip.open(filename, 'rb') as f:
        return pickle_load(f, encoding='latin-1')


def load_data():
    """Get data with labels, split into training, validation and test set."""
    data = _load_data()
    X_train, y_train = data[0]
    X_valid, y_valid = data[1]
    X_test, y_test = data[2]
    y_train = numpy.asarray(y_train, dtype=numpy.int32)
    y_valid = numpy.asarray(y_valid, dtype=numpy.int32)
    y_test = numpy.asarray(y_test, dtype=numpy.int32)

    return dict(
        X_train=X_train,
        y_train=y_train,
        X_valid=X_valid,
        y_valid=y_valid,
        X_test=X_test,
        y_test=y_test,
        num_examples_train=X_train.shape[0],
        num_examples_valid=X_valid.shape[0],
        num_examples_test=X_test.shape[0],
        input_dim=X_train.shape[1],
        output_dim=10,
    )


def nn_example(data):
    net1 = NeuralNet(
        layers=[('input', layers.InputLayer),
                ('hidden', layers.DenseLayer),
                ('output', layers.DenseLayer),
                ],
        # layer parameters:
        input_shape=(None, 28*28),  # 96x96 input pixels per batch
        hidden_num_units=100,  # number of units in hidden layer
        output_nonlinearity=None,  # output layer uses identity function
        output_num_units=10,  # 10 target values

        # optimization method:
        update=nesterov_momentum,
        update_learning_rate=0.01,
        update_momentum=0.9,

        max_epochs=400,  # we want to train this many epochs
        verbose=1,
        )
    print(data['X_train'].shape)
    print(data['y_train'].shape)
    net1.fit(data['X_train'], data['y_train'])

    # print(data['X_test'][0])
    # print(net1.predict(data['X_test'][0]))
    # print(data['y_test'][0])


def main():
    data = load_data()
    print("Got %i testing datasets." % len(data['X_train']))
    # print("Get trainingset")
    # training = get_labeled_data('train-images-idx3-ubyte.gz',
    #                             'train-labels-idx1-ubyte.gz')
    nn_example(data)

if __name__ == '__main__':
    main()

```

**Comment by MartinThoma** [comment]
The issue was simply that I didn't have the right input / output shape.

**Comment by karimmansour** [comment]
What are the right input and output shapes?
