### ISSUE TITLE
Error in from nolearn.lasagne

### ISSUE THREAD

**Issue by MammadTavakoli** [dnouri/nolearn#171]
Hi 
I installed theano and nolearn wgity Anaconda2-2.4.0-Windows-x86_64 in Windows 10.
but i get the "ImportError: cannot import name futil" error.

How i can the solve it?

thanks.

**Comment by cancan101** [comment]
`futil` might not exist on windows.

**Comment by dnouri** [comment]
What does the stack trace look like?

**Comment by MammadTavakoli** [comment]
the error is this 


Traceback (most recent call last):

  File "<ipython-input-20-ba7644ac83cd>", line 1, in <module>
    runfile('G:/CNN/kaggle_forest_cover_type-master/my_model.py', wdir='G:/CNN/kaggle_forest_cover_type-master')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "G:/CNN/kaggle_forest_cover_type-master/my_model.py", line 11, in <module>
    from sklearn import cross_validation

  File "C:\Anaconda2\lib\site-packages\sklearn\cross_validation.py", line 32, in <module>
    from .metrics.scorer import check_scoring

  File "C:\Anaconda2\lib\site-packages\sklearn\metrics\__init__.py", line 7, in <module>
    from .ranking import auc

  File "C:\Anaconda2\lib\site-packages\sklearn\metrics\ranking.py", line 30, in <module>
    from ..utils.stats import rankdata

  File "C:\Anaconda2\lib\site-packages\sklearn\utils\stats.py", line 2, in <module>
    from scipy.stats import rankdata as _sp_rankdata

  File "C:\Anaconda2\lib\site-packages\scipy\stats\__init__.py", line 321, in <module>
    from .stats import *

  File "C:\Anaconda2\lib\site-packages\scipy\stats\stats.py", line 183, in <module>
    from . import futil

ImportError: cannot import name futil

**Comment by MammadTavakoli** [comment]
the error is this 


Traceback (most recent call last):

  File "<ipython-input-20-ba7644ac83cd>", line 1, in <module>
    runfile('G:/CNN/kaggle_forest_cover_type-master/my_model.py', wdir='G:/CNN/kaggle_forest_cover_type-master')

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 71, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "G:/CNN/kaggle_forest_cover_type-master/my_model.py", line 11, in <module>
    from sklearn import cross_validation

  File "C:\Anaconda2\lib\site-packages\sklearn\cross_validation.py", line 32, in <module>
    from .metrics.scorer import check_scoring

  File "C:\Anaconda2\lib\site-packages\sklearn\metrics\__init__.py", line 7, in <module>
    from .ranking import auc

  File "C:\Anaconda2\lib\site-packages\sklearn\metrics\ranking.py", line 30, in <module>
    from ..utils.stats import rankdata

  File "C:\Anaconda2\lib\site-packages\sklearn\utils\stats.py", line 2, in <module>
    from scipy.stats import rankdata as _sp_rankdata

  File "C:\Anaconda2\lib\site-packages\scipy\stats\__init__.py", line 321, in <module>
    from .stats import *

  File "C:\Anaconda2\lib\site-packages\scipy\stats\stats.py", line 183, in <module>
    from . import futil

ImportError: cannot import name futil

**Comment by dnouri** [comment]
Looks like a problem with your scipy installation, then.
