### ISSUE TITLE
Impossible to use a gpu on Amazon EC2

### ISSUE THREAD

**Issue by MatthieuBizien** [dnouri/nolearn#2]
I wanted to use the g2.2xlarge plan on amazon EC2 for fitting a DBN, but It doesn't detect the GPU. Cuda and Cudamat are installed, and the sample code from NVidia _deviceQuery_ correctly detect the GPU. My code work well with the CPU alone.

```
net = DBN(
    [x.shape[1], nhidden, 2],
    scales=[numpy.sqrt(6/x_train.shape[1]/nhidden), numpy.sqrt(6/nhidden)],
    epochs=50,
    verbose=1,
    dropouts=0.5,
    minibatch_size = 64,
    minibatches_per_epoch = 4500 # So we have 288k items 
    )
net.fit(x, y)
```

```
$ export GNUMPY_USE_GPU=yes; python DBN\ with\ Nolearn.py 
((304007, 683), (304007, 1)) ((5000, 683), (5000, 1)) ((5000, 683), (5000, 1)) (96136, 683)
[DBN] fitting X.shape=(304007, 683)
[DBN] layers [683, 30, 2]
Traceback (most recent call last):
  File "DBN with Nolearn.py", line 112, in <module>
    net.fit(x, y)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/dbn.py", line 340, in fit
    self.net_ = self._build_net(X, y)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/dbn.py", line 246, in _build_net
    v(self.uniforms),
  File "/usr/local/lib/python2.7/dist-packages/gdbn/dbn.py", line 84, in buildDBN
    initialBiases = [gnp.garray(0*num.random.rand(1, layerSizes[i])) for i in range(1, len(layerSizes))]
  File "/usr/local/lib/python2.7/dist-packages/gnumpy.py", line 724, in __init__
    cm = _new_cm(npa.size)
  File "/usr/local/lib/python2.7/dist-packages/gnumpy.py", line 215, in _new_cm
    _init_gpu()
  File "/usr/local/lib/python2.7/dist-packages/gnumpy.py", line 80, in _init_gpu
    if _boardId==-1: raise Exception('No gpu board is available. gnumpy will not function. Consider telling it to run on the CPU by setting environment variable GNUMPY_USE_GPU to "no".')
Exception: No gpu board is available. gnumpy will not function. Consider telling it to run on the CPU by setting environment variable GNUMPY_USE_GPU to "no".

$ ./NVIDIA_CUDA-5.5_Samples/bin/x86_64/linux/release/deviceQuery
Set compute mode to DEFAULT for GPU 0000:00:03.0.
All done.
./NVIDIA_CUDA-5.5_Samples/bin/x86_64/linux/release/deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GRID K520"
  CUDA Driver Version / Runtime Version          5.5 / 5.5
  CUDA Capability Major/Minor version number:    3.0
  Total amount of global memory:                 4096 MBytes (4294770688 bytes)
  ( 8) Multiprocessors, (192) CUDA Cores/MP:     1536 CUDA Cores
  GPU Clock rate:                                797 MHz (0.80 GHz)
  Memory Clock rate:                             2500 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(65536), 2D=(65536, 65536), 3D=(4096, 4096, 4096)
  Maximum Layered 1D Texture Size, (num) layers  1D=(16384), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(16384, 16384), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Bus ID / PCI location ID:           0 / 3
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 5.5, CUDA Runtime Version = 5.5, NumDevs = 1, Device0 = GRID K520
Result = PASS
```

**Comment by dnouri** [comment]
I'm afraid I cannot support `nolearn.dbn` any longer; it's already removed from master.  May I suggest you give `nolearn.lasagne` a try instead? It's got a lot of improvements over the `dbn` module.
