### ISSUE TITLE
Getting Type Error while training Convnet using nolearn.lasagne

### ISSUE THREAD

**Issue by nishankb1012** [dnouri/nolearn#273]
I am trying to train convnet model using nolearn.lasagne but it seems like there is some issue with labels type. Any help is appreciated. Thanks a lot.

code:

import os
import numpy as np
from PIL import Image

import theano
import lasagne
from lasagne import layers
from lasagne.updates import nesterov_momentum
from nolearn.lasagne import NeuralNet
from sklearn.preprocessing import LabelEncoder

def traindata(path):
    label_paths=[os.path.join(path,'train',f)
                 for f in os.listdir(os.path.join(path,'train'))]
    # feature variables
    images_train=[]
    labels_train=[]
    # Traverse along the labeled folders
    for label_path in label_paths:
        # Extract images belong to the label
        image_paths=[os.path.join(label_path,q) for q in os.listdir(label_path)] 
        label=int((os.path.split(label_path)[1])[1]) # a numeric value (0-9)
        # Traverse along the images
        for image_path in image_paths:
            image_pil=Image.open(image_path).convert('L')
            image=np.array(image_pil,'uint8')
            image=image.reshape((-1,1,640 ,480 ))
            images_train.append(image)
            labels_train.append(label)
    return images_train,labels_train

path="I:/abd" # location of train data having subfolders for each class which contain images.

images_train, labels_train=traindata(path)
labels_train= np.array(labels_train).astype(np.int32)

net1 = NeuralNet(
    layers=[('input', layers.InputLayer),
            ('conv2d1', layers.Conv2DLayer),
            ('maxpool1', layers.MaxPool2DLayer),
            ('conv2d2', layers.Conv2DLayer),
            ('maxpool2', layers.MaxPool2DLayer),
            ('dropout1', layers.DropoutLayer),
            ('dense', layers.DenseLayer),
            ('dropout2', layers.DropoutLayer),
            ('output', layers.DenseLayer),
            ],
    # input layer
    input_shape=(None, 1,640,480),
    # layer conv2d1
    conv2d1_num_filters=32,
    conv2d1_filter_size=(20, 20),
    conv2d1_nonlinearity=lasagne.nonlinearities.rectify,
    conv2d1_W=lasagne.init.GlorotUniform(),  
    # layer maxpool1
    maxpool1_pool_size=(2, 2),    
    # layer conv2d2
    conv2d2_num_filters=32,
    conv2d2_filter_size=(20, 20),
    conv2d2_nonlinearity=lasagne.nonlinearities.rectify,
    # layer maxpool2
    maxpool2_pool_size=(2, 2),
    # dropout1
    dropout1_p=0.5,    
    # dense
    dense_num_units=256,
    dense_nonlinearity=lasagne.nonlinearities.rectify,    
    # dropout2
    dropout2_p=0.5,    
    # output
    output_nonlinearity=lasagne.nonlinearities.softmax,
    output_num_units=10,
    # optimization method params
    update=nesterov_momentum,
    update_learning_rate=0.01,
    update_momentum=0.9,
    max_epochs=10,
    verbose=1,
    )

#Training
conv=net1.fit(images_train,labels_train)

Output:

Traceback (most recent call last):
  File "finalproject.py", line 97, in <module>
    conv=net1.fit(images_train,labels_train)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\nolearn\lasagne
\base.py", line 293, in fit
    self.train_loop(X, y)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\nolearn\lasagne
\base.py", line 300, in train_loop
    X, y, self.eval_size)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\nolearn\lasagne
\base.py", line 404, in train_test_split
    X_train, y_train = X[train_indices], y[train_indices]
TypeError: only integer arrays with one element can be converted to an index

**Comment by BenjaminBossan** [comment]
Hi,

there seems to be a problem with your numpy arrays. I believe it's best if you could run with pdb and inspect your `X`, `y` and `train_indices`.

Btw., when you paste code blocks, use triple back-ticks before and after:

\`\`\`
def fun(x):
    return x + 1
\`\`\`

becomes:

```
def fun(x):
    return x + 1
```

**Comment by nishankb1012** [comment]
Sir,
 First of all Thank you very much for replying. As directed above i have tried using pdb for debugging but it is in turn giving me an error. Can you please help!
```
[snakes] C:\Theano-master>python -m pdb finalproject.py
Traceback (most recent call last):
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 1661, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 1542, in _runsc
ript
    self.run(statement)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\theano-master\finalproject.py", line 1, in <module>
    import os
  File "c:\theano-master\finalproject.py", line 1, in <module>
    import os
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\bdb.py", line 48, in trace_di
spatch
    return self.dispatch_line(frame)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\bdb.py", line 66, in dispatch
_line
    self.user_line(frame)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 259, in user_li
ne
    self.interaction(frame, None)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 2
44, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 7
98, in print_stack_entry
    print('[%d] >' % frame_index, file=self.stdout, end=' ')
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\codecs.py", line 374, in writ
e
    self.stream.write(data)
TypeError: must be str, not bytes
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
Traceback (most recent call last):
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 1661, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 1542, in _runsc
ript
    self.run(statement)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\bdb.py", line 431, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "c:\theano-master\finalproject.py", line 1, in <module>
    import os
  File "c:\theano-master\finalproject.py", line 1, in <module>
    import os
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\bdb.py", line 48, in trace_di
spatch
    return self.dispatch_line(frame)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\bdb.py", line 66, in dispatch
_line
    self.user_line(frame)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 259, in user_li
ne
    self.interaction(frame, None)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 2
44, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 7
98, in print_stack_entry
    print('[%d] >' % frame_index, file=self.stdout, end=' ')
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\codecs.py", line 374, in writ
e
    self.stream.write(data)
TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\runpy.py", line 170, in _run_
module_as_main
    "__main__", mod_spec)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\runpy.py", line 85, in _run_c
ode
    exec(code, run_globals)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\_pdbpp_path_hac
k\pdb.py", line 5, in <module>
    os.path.dirname(os.path.dirname(__file__)), 'pdb.py'), 'exec'))
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 1
096, in <module>
    pdb.main()
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\pdb.py", line 1680, in main
    pdb.interaction(None, t)
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 2
44, in interaction
    self.print_stack_entry(self.stack[self.curindex])
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\site-packages\pdb.py", line 7
98, in print_stack_entry
    print('[%d] >' % frame_index, file=self.stdout, end=' ')
  File "C:\Users\Nishank\Anaconda3\envs\snakes\lib\codecs.py", line 374, in writ
e
    self.stream.write(data)
TypeError: must be str, not bytes
```

**Comment by EliasVansteenkiste** [comment]
[Check this stackoverflow question](http://stackoverflow.com/questions/33144039/typeerror-only-integer-arrays-with-one-element-can-be-converted-to-an-index-3)
I think your labels and data must be numpy arrays, in your code they are lists of numpy arrays.

Maybe also do a sanity check on the shapes of `X`, `y` and `train_indices`.

**Comment by BenjaminBossan** [comment]
Yes, please verify that X and y are correct numpy arrays:
```
print(type(X), type(y))
print(X.shape, y.shape)
```

Why your pdb call does not work is not clear to me. Perhaps you can set it manually at the corresponding line of code:
```
import pdb
...
pdb.set_trace()
```

**Comment by nishankb1012** [comment]
Thanks for the suggestions. I could realize that X and y were not correct numpy arrays and therefore I have converted both of them to class: numpy.ndarray explicitly and with the shape 
X -> (22000,1,100,100) 
y -> (22000,)
and now on training the same model and testing with other images (30000 data sets belonging to different classes) I could see that all of the images are getting classified under one single label (class). To understand it clearly I have also used .predict_proba to get the probabilities under each label but the result show 1 under one specific label and 0 under the rest for all the images. 
Could anyone please help?

**Comment by BenjaminBossan** [comment]
Somehow the net does not learn anything from the data and comes up with the best solution it can do. There could be numerous reasons for why that happens. To solve this remotely is almost impossible. Please search for hyper-parameter optimization, check that your data are correct (shuffling, reshaping, etc. could be sources of error). One of the first things I check when my net does not learn is the learning rate, so maybe try that.

Otherwise, if your original issue is solved, I believe this thread can be closed.

**Comment by nishankb1012** [comment]
Thank you very much for the suggestions...
