### ISSUE TITLE
TypeError when l1 regularization in objective: unsupported operand type(s) for *: 'TensorVariable' and 'function'

### ISSUE THREAD

**Issue by Pengwei-Yang** [dnouri/nolearn#297]
Try to add l1 regularization to NeuralNet by setting "objective_l1 = regularization.l1" while "objective_loss_function =categorical_crossentropy". TypeError show up:
TypeError: unsupported operand type(s) for *: 'TensorVariable' and 'function'

The traceback is as the following:

Traceback (most recent call last):
  File "DANN_Tuning_penalized.py", line 127, in <module>
    grid_search.fit(X, y)
  File "/usr/lib64/python2.7/site-packages/sklearn/grid_search.py", line 804, in fit
    return self._fit(X, y, ParameterGrid(self.param_grid))
  File "/usr/lib64/python2.7/site-packages/sklearn/grid_search.py", line 553, in _fit
    for parameters in parameter_iterable
  File "/usr/lib64/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/usr/lib64/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/usr/lib64/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/usr/lib64/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/usr/lib64/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/usr/lib64/python2.7/site-packages/sklearn/cross_validation.py", line 1531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 505, in fit
    self.initialize()
  File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 346, in initialize
    self.y_tensor_type,
  File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 453, in _create_iter_funcs
    layers, target=y_batch, **objective_kw)
  File "/usr/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 169, in objective
    loss += regularization.regularize_layer_params(layers.values(), regularization.l1) * l1
TypeError: unsupported operand type(s) for *: 'TensorVariable' and 'function'

Any suggestions to fix the error? Thanks very much.

**Comment by BenjaminBossan** [comment]
You should pass a value that indicates how strong regularization should be, e.g. `objective_l1=0.001`.

**Comment by Pengwei-Yang** [comment]
Thanks very much for the inputs! My bad for the error. The module works fine with the value. By the way, any suggestions about value grid for l1 strength if using grid search and if applying different l1 strength to different layers? Thanks,

**Comment by BenjaminBossan** [comment]
My suggestion is to not use l1 at all, it has never helped me (except if you really really need sparse weights). Try dropout or l2 if your model overfits.

Since the question is solved, I will close it.
