### ISSUE TITLE
OSError: could not read bytes when trying to fetch mldata

### ISSUE THREAD

**Issue by RohanVB** [dnouri/nolearn#308]
I tried 

`dataset = fetch_mldata('MNIST original', data_home='/Users/my_name/Virtualenv/virt1/lib/python3.5/site-packages/sklearn/datasets/')`

and 

`dataset = fetch_mldata('MNIST original')
`

I get the following error, which states : OSError: could not read bytes when trying to fetch mldata.
Here is the entire Traceback.
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/my_name/Virtualenv/virt1/lib/python3.5/site-packages/sklearn/datasets/mldata.py", line 158, in fetch_mldata
    matlab_dict = io.loadmat(matlab_file, struct_as_record=True)
  File "/Users/my_name/Virtualenv/virt1/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 136, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/Users/my_name/Virtualenv/virt1/lib/python3.5/site-packages/scipy/io/matlab/mio5.py", line 292, in get_variables
    res = self.read_var_array(hdr, process)
  File "/Users/my_name/Virtualenv/virt1/lib/python3.5/site-packages/scipy/io/matlab/mio5.py", line 252, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "scipy/io/matlab/mio5_utils.pyx", line 673, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/mio5_utils.c:7119)
  File "scipy/io/matlab/mio5_utils.pyx", line 703, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/mio5_utils.c:6244)
  File "scipy/io/matlab/mio5_utils.pyx", line 776, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/mio5_utils.c:7572)
  File "scipy/io/matlab/mio5_utils.pyx", line 448, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/mio5_utils.c:4323)
  File "scipy/io/matlab/mio5_utils.pyx", line 353, in scipy.io.matlab.mio5_utils.VarReader5.read_element (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/mio5_utils.c:3913)
  File "scipy/io/matlab/streams.pyx", line 92, in scipy.io.matlab.streams.GenericStream.read_string (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/streams.c:2182)
  File "scipy/io/matlab/streams.pyx", line 79, in scipy.io.matlab.streams.GenericStream.read_into (/private/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/pip-rx828oer-build/scipy/io/matlab/streams.c:1977)
OSError: could not read bytes

```

**Comment by BenjaminBossan** [comment]
The error seems to be unrelated to nolearn, maybe search for a solution in the sklearn issues (which is where `fetch_mldata` comes from)?

**Comment by jash101** [comment]
Facing the same issue
