### ISSUE TITLE
Shape mismatch in dbn.fit

### ISSUE THREAD

**Issue by joaopcanario** [dnouri/nolearn#54]
Hi,

When I'm passing my dataset (cohn-kanade dataset) for lib training, I receive this follow error. Did anyone already saw something similar? (Right now, just for test, I'm using only a small part of dataset)

[DBN] fitting X.shape=(365, 784)
[DBN] layers [784, 300, 10]
[DBN] Fine-tune...
Traceback (most recent call last):
  File "deep.py", line 46, in <module>
    dbn.fit(trainX, trainY)
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/nolearn/dbn.py", line 409, in fit
    self.use_dropout,
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gdbn/dbn.py", line 202, in fineTune
    err, outMB = step(inpMB, targMB, self.learnRates, self.momentum, self.L2Costs, useDropout)
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gdbn/dbn.py", line 303, in stepNesterov
    errSignals, outputActs, error = self.fpropBprop(inputBatch, targetBatch, useDropout)
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gdbn/dbn.py", line 262, in fpropBprop
    outputErrSignal = -self.outputActFunct.dErrordNetInput(targetBatch, self.state[-1], outputActs)
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gdbn/activationFunctions.py", line 138, in dErrordNetInput
    return acts - targets
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gnumpy.py", line 965, in __sub__
    else: return self + -as_garray(other) # if i need to broadcast, making use of the row add and col add methods is probably faster
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gnumpy.py", line 926, in __add__
    def __add__(self, other): return _check_number_types(self._broadcastable_op(as_garray_or_scalar(other), 'add'))
  File "/Users/jpcanario/.virtualenvs/msdegree/lib/python2.7/site-packages/gnumpy.py", line 614, in _broadcastable_op
    if reduce(operator.or_, ( other.shape[i] not in (1, self.shape[i]) for i in range(self.ndim)), False): raise ValueError('shape mismatch: objects cannot be broadcast to a single shape')

I've no idea what is causing the problem. Just describing the dataset and my steps before training.

My dataset:
- All images are colored and have 640x490 pixels.

Before training (After loaded Image I do the follow steps):
- I convert to grayscale
- Cut the image to get 490x490 pixels
- Resize each image to 28x28.
- Finally, I change the image shape, from matrix to a vector, using the following command

  _im = im.reshape(1, im.shape[0]*im.shape[1])_

Thanks in advance

**Comment by joaopcanario** [comment]
Problem solved!

I finally figured out what it happening. In my dataset labels, some images are labeled wrong. So, because of that, the number of outputs that my labels has was different from the number of labels output that I really have.
