### ISSUE TITLE
TypeError with convolutional layer: __init__() takes at least 3 arguments

### ISSUE THREAD

**Issue by Rachnog** [dnouri/nolearn#83]
Hello, guys!

Everything worked really well with Lasagne and Nolearn,
until I reinstalled my Ubuntu. I've configured everything and ran some tests like lasagne tutorials and everything was okay,
so I wanted to use my old code with network like:

```
net2 = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('conv1', layers.Conv2DLayer),
        ('pool1', layers.MaxPool2DLayer),
        ('conv2', layers.Conv2DLayer),
        ('pool2', layers.MaxPool2DLayer),
        ('conv3', layers.Conv2DLayer),
        ('pool3', layers.MaxPool2DLayer),
        ('hidden4', layers.DenseLayer),
        ('hidden5', layers.DenseLayer),
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 3, PIXELS, PIXELS),
    conv1_num_filters=32, conv1_filter_size=(3, 3), pool1_ds=(2, 2),
    conv2_num_filters=64, conv2_filter_size=(2, 2), pool2_ds=(2, 2),
    conv3_num_filters=128, conv3_filter_size=(2, 2), pool3_ds=(2, 2),
    hidden4_num_units=500, hidden5_num_units=500,
    output_num_units=50, output_nonlinearity=nonlinearities.softmax,
    update_learning_rate=0.01,
    update_momentum=0.9,
    regression=False,
    max_epochs=1000,
    verbose=1,
        # Training test-set split
    eval_size = 0.2
    )
```

In fact it was a bit larger, but whatever. And it gives me such error:

```
 Start training...
/usr/local/lib/python2.7/dist-packages/Lasagne-0.1dev-py2.7.egg/lasagne/init.py:86: UserWarning: The uniform initializer no longer uses Glorot et al.'s approach to determine the bounds, but defaults to the range (-0.01, 0.01) instead. Please use the new GlorotUniform initializer to get the old behavior. GlorotUniform is now the default for all layers.
  warnings.warn("The uniform initializer no longer uses Glorot et al.'s "
Traceback (most recent call last):
  File "las_mnist.py", line 200, in <module>
    net2.fit(X, y)
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne.py", line 138, in fit
    out = self._output_layer = self.initialize_layers()
  File "/usr/local/lib/python2.7/dist-packages/nolearn/lasagne.py", line 369, in initialize_layers
    layer = layer_factory(layer, **layer_params)
TypeError: __init__() takes at least 3 arguments (2 given)
```

Why I think, it's something with convolutions,
because network with DenseLayers and Dropouts only runs well:

```
net1 = NeuralNet(
    layers=[
        ('input', layers.InputLayer),
        ('hidden1', layers.DenseLayer),
        ('dropout1', layers.DropoutLayer),  # !
        ('hidden2', layers.DenseLayer),
        ('dropout2', layers.DropoutLayer),  # !
        ('hidden3', layers.DenseLayer),
        ('dropout3', layers.DropoutLayer),  # !
        ('output', layers.DenseLayer),
        ],
    input_shape=(None, 3, PIXELS, PIXELS), #None in the first axis indicates that the batch size can be set later
    dropout1_p=0.5,  # !
    hidden1_num_units=2000,
    dropout2_p=0.5,  # !
    hidden2_num_units=1000,
    dropout3_p=0.5,  # !
    hidden3_num_units=500,

    output_num_units=50, output_nonlinearity=nonlinearities.softmax,
    # learning rate parameters
    update_learning_rate=0.01,
    update_momentum=0.9,
    regression=False,
    # We only train for 10 epochs
    max_epochs=100,
    verbose=1,
    # Training test-set split
    eval_size = 0.2
        )
```
 
Please help me, if you have some ideas how to handle it.
Thank you very much!

**Comment by dnouri** [comment]
It looks like you've updated your version of Lasagne inbetween.  Some of the conv and pool layer parameters [have been renamed](https://groups.google.com/forum/#!topic/lasagne-users/a0TYC1JlqeQ/discussion) and you'll have to adjust your code.

But yeah, make also sure you're running versions of nolearn and Lasagne that are [known to work together](https://github.com/dnouri/nolearn/blob/master/requirements.txt#L4).  So if you're getting the latest nolearn from Git master, make sure you're using its requirements.txt to install Lasagne:

```
pip uninstall Lasagne && \
pip install -r https://raw.githubusercontent.com/dnouri/nolearn/master/requirements.txt
```
